### PR TITLE
This has my quiz also I moved my game stuff to a new workshop.

### PR DESCRIPTION
**Pull request by k0789885**

### CODE REVIEW

**Review by chrisortman — APPROVED** [review]
Looks good

**Comment by k0789885** [comment]
Don't forget to check out those apps I recommend. (Learn python, Learn
Java, Learn C++, etc...) I feel like even you could learn something from
them.

**Comment by chrisortman** [comment]
I think I can learn quite a bit from a lot of things yet ;)

**Comment by chrisortman** [comment]
It also looks like they have a web based version, so we might be making use
of this. Thanks for finding

**Pull request merged**
